# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer', models.IntegerField()),
                ('slug', models.CharField(max_length=200)),
                ('material', models.CharField(max_length=200)),
                ('current_layer', models.IntegerField()),
                ('machine_type', models.CharField(max_length=50)),
                ('machine_index', models.CharField(max_length=50)),
                ('completion_percentage', models.IntegerField()),
                ('job_name', models.CharField(max_length=200)),
            ],
        ),
    ]
